### PR TITLE
Adding New Examples

### PR DESCRIPTION
**Pull request by geekgirljoy**
# Adding New Examples

## What was done?
- Created sub-folders for all projects in the examples folder to maintain order.
- Added completion notification to simple_train.php and hyperlink to simple_train.php.
- Added AND, NAND, NOR, NOT, OR, XNOR example training data. 
- Added OCR Example. 
- Added Pathfinder Example. 
- Updated README.md to reflect the additional examples and added links to code.
- Updated package.xml.

All example code has been tested to work as expected.

### OCR

OCR is a practical example of Optical Character Recognition using FANN. While this example is limited and does make mistakes, the concepts illustrated by OCR can be applied to a more robust stacked network that uses feature extraction and convolution layers to recognize text of any font in any size image. 

### Pathfinder

Pathfinder is an example of a neural network that is capable of plotting an 8 direction step path from a starting position in a 5x5 grid to an ending position in that grid. To keep the Pathfinder example simple it is not trained to deal with walls or non-traversable terrain however it would be very easy to add that by adding additional training.

### CODE REVIEW

**Comment by bukka** [comment]
@geekgirljoy That looks really great! Thanks a lot for the PR.

Just one question before I merge it and make it part of the distributed package. Have you generated the images for the numbers or are they from some free source so we can freely distribute them?

**Comment by geekgirljoy** [comment]
@bukka Thanks! I really appreciate what PHP FANN is and what it allows people to do! 

I think everyone who wants to work with ANN's should definitely give PHP FANN a try! 

These examples are subjects of some upcoming blog posts I am writing that will cover how to use these examples and what steps someone might take if they wanted to improve them and use them in a project of their own. 

As for the images, I generated them programmatically using the GD library:  [http://php.net/manual/en/book.image.php](http://php.net/manual/en/book.image.php) and was initially going to include that script as well as the script that creates the training data from the images however I was not sure if that would be out of place and opted to exclude it in favor of simply a functional example. If you think it's appropriate to include those scripts in the example I would be happy to clean up my code and add that to the PR. 

Below is the code I used to create the images, please note I have not optimized this code in any way and it's still rough and I would want to clean it up before committing it to the project should you want to do that.

```
<?php

/*
	This function actually creates the images
	
	GenerateTrainingImages() will call this function for you
*/
function NewImage($char, $curr_image, $x , $y, $logfile){
	/* size the images */
	$width = 10; // px
	$height= 16; // px

	/* create, style, draw */
	$image = @imagecreate($width, $height) or die("Unable to Initialize Image Stream");
	$background_color = imagecolorallocate($image, 0, 0, 0);
	$text_color = imagecolorallocate($image, 255, 255, 255);
	imagestring($image, 5, $x, $y,  chr($char), $text_color);
	
	/* create the filename */
	$file_name = $curr_image . '.png';
	
	/* output then destroy image*/
	imagepng($image, './images/' . $file_name);
	imagedestroy($image);
	
	/* write to log file */	
	fwrite($logfile, $curr_image . ' ' . chr($char). PHP_EOL);
}

/*
	This function manages the image creation.
	
	Call this function to create a new image training set
*/
function GenerateTrainingImages() {	
	/* the images folder was already created */
	if (file_exists('images')) {
        echo "The images folder already exists, no changes made!<br>" . PHP_EOL;
    }
	else{ /* if there isn't an images folder, create one */
		echo "The images folder does not exists, creating one... ";
		if (!mkdir("images", 0755, true)) {
			die('fail! Ending program.');
		}else{
			echo 'success!<br>' . PHP_EOL;
		}
	}
	
    /* create log file of image output */
	$logfile = fopen("images/generate_images.log", "w") or die("Unable to open: " . $logfile . '. Ending program.');
	
	/* current number of generated images */	
	$curr_image = 0;
	
	/* 
	    char output range
		start: ascii dec 33 (!) 
		stop:  ascii dec 126 (~) 
	*/
	for($i = 33; $i <= 126; $i++) {

		NewImage($i, $curr_image, 1, 0, $logfile);
		$curr_image++;
	}
	
	/* Close log file */
	fclose($logfile);
}

/* generate training images */
GenerateTrainingImages();

/* announce completion and link to next step */
echo 'All Done! Now run <a href="generate_training_data.php">generate_training_data.php</a><br>' . PHP_EOL;


?>

```


Additionally I have been considering changing the Pathfinder example to generate the start and stop positions randomly for the testing rather than hard coding the tests as I think showing people that test might lead to more interesting results. However, that might also be more complicated and it's best that the examples be simple enough that people can quickly see what is going on so that might be more confusing than helpful.

Please let me know if I was unclear about anything or if there is anything further I can assist your with.

~geekgirljoy

**Comment by geekgirljoy** [comment]
@bukka Not sure if this is the right place to discuss this with you however I wanted to test PHP FANN on Windows and there doesn't seem to be any additional instructions other than to say that there are DLL's available. I have attempted installing the DLL's on a windows 8 machine and I simply cannot get the FANN DLL's registered. I obtained the DLL's from here: http://pecl.php.net/package/fann and placed them in both: C:\Windows\System32 & C:\Windows\SysWOW64

As admin in an elivated command prompt I issue the register DLL command but each of these fail: 

C:\WINDOWS\system32>regsvr32 php_fann.dll
C:\Windows\SysWOW64>regsvr32 php_fann.dll
C:\Windows>regsvr32 C:\WINDOWS\system32\php_fann.dll
C:\Windows\SysWOW64>regsvr32 C:\WINDOWS\sysWOW64\php_fann.dll

The exact message is:

The module "php_fann.dll" failed to load. Make sure the binary is stored at the specified path or debug it to check for problems with the binary or dependent .DLL files. The specified module cannot be found.

Seemingly windows cannot see the DLL but it's there. Can you advise?

**Comment by EagleErwin** [comment]
I think you have to place the php_fann.dll in your <php_root>/ext folder (see your php.ini, option extension_dir). There are all the other DLL's located as well. No need to call regsvr32, just copy the file to that directory and enable it in your php.ini.

**Comment by geekgirljoy** [comment]
@EagleErwin Thanks for the reply! Unfortunately this too does not seem to be working. 

I am using the XAMPP web server so I placed copies of the DLL's in this location: C:\xampp\php\ext

I then updated php.ini 'Dynamic Extensions' section to include:
extension=php_fann.dll
extension=fanndouble.dll

I then restarted Apache and tested but that did not work.  I then restarted the computer and that did not resolve the problem.

If I run php.exe I get the following errors:

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_fann.dll' - %1 is not a valid Win32 application.
in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\fanndouble.dll' - %1 is not a valid Win32 application.
in Unknown on line 0

This seems to indicate an issue with the DLL's? I downloaded the dll's again tried once more with the same results. Suggestions?

**Comment by EagleErwin** [comment]
The only thing I can think about, is that you are using the x86 DLL on a x64 PHP version, or vice versa.
You check your `phpinfo()`, make sure the DLL matches the architecture that is shown at "`PROCESSOR_ARCHITECTURE`" at the "`Environment`" section.

**Comment by bukka** [comment]
@geekgirljoy Merged! Thanks!

As of the win issue, not really sure how to use it with xampp as I'm not really a win user. If you are still having issue, I would suggest to create a new issue. I plan to look on the Win issues at some point in the future if I find some time (there are already couple of open issues) or someone else might be able to help.

**Pull request merged**
